spring.application.name=notification-service
server.port=8080
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
# App Properties
app.frontend.url=${frontend.url}
app.clients.auth-service.name=auth-service
app.clients.main-service.name=main-service
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${smtp.username}
spring.mail.password=${smtp.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Observability
management.health.readinessState.enabled=true
management.health.livenessState.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=notification-service
#RabbitMQ
spring.rabbitmq.host=${rabbit.host}
spring.rabbitmq.port=${rabbit.port}
spring.rabbitmq.username=${rabbit.username}
spring.rabbitmq.password=${rabbit.password}
#Logging
logging.level.com.crm.notification=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.web.socket.server.support=DEBUG
