spring.application.name=notification-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Logging
logging.level.com.crm.notification=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.web.socket.server.support=DEBUG
